services:
  mongo:
    image: mongo
    command: mongod --bind_ip_all
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=secret
    ports:
      - 27018:27017   # Alterar a porta aqui
