version: "3.1"
services:
  mongo:
    image: mongo
    command: mongod --bind_ip_all  
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=secret
    ports:
      - 27017:27017
